config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :profile, only: [:show, :edit, :update]

  get 'render/index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # DEFAULT ROUTE
  root "render#index"


  ###################
  # LÓGICA DE RUTAS #
  ###################
  # -> Artículos (Objeto)
  post "/articles", to: "articles#create"
  patch "/articles/:article_id", to: "articles#update"

  # -> Blogs (Objeto)
  post "/blogs", to: "blogs#create"
  patch "/blogs/:blog_id", to: "blogs#update"
  delete "/blogs/:blog_id", to: "blogs#delete"





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :blogs
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :article
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :profile_picture, ProfilePictureUploader
  # Validaciones
  validates :first_name, :last_name, :phone, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # POST /articles
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:created] = true
      redirect_to root_path
    else
      render "render/index", status: :unprocessable_entity
    end
  end

  def update
    @article = Article.find(params[:article_id])

    if @article.update(article_params)
      redirect_to root_path(view: "article", query: @article.id), notice: "Artículo actualizado"

    else
      render "render/index", locals: { view: "article", query: @article.id }, status: :unprocessable_entity
    end
  end


  def article_params
    params.require(:article).permit(:title, :description, :info_type, 
    :references);
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # POST /articles
  def create
    @blog = Blog.new(blog_params);
    if @blog.save
      redirect_to root_path, notice: "Blog creado correctamente"
    else
      render "render/index", locals: { view: "create_blog_form", article_id: @blog.article_id }, status: :unprocessable_entity
    end
  end

  def update
    @blog = Blog.find(params[:blog_id])

    if @blog.update(blog_params)
      redirect_to root_path(view: "blog", query: @blog.id), notice: "Artículo actualizado"

    else
      render "render/index", locals: { view: "blog", query: @blog.id }, status: :unprocessable_entity
    end
  end

  def delete
    if Blog.exists?
      @blog = Blog.find(params[:blog_id])
      @blog.destroy
      redirect_to root_path, notice: "Blog eliminado correctamente"
    else
      render "render/index", locals: { view: "blog_form", query: params[:blog_id] }, status: :unprocessable_entity
    end
  end

  def blog_params
    params.require(:blog).permit(:title, :description, :editors, :info_type, 
    :related_info, :article_id);
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user! # Asegura que el usuario esté autenticado
  
    def show
      @profile = current_user.profile || current_user.build_profile
    end
  
    def edit
      @profile = current_user.profile || current_user.build_profile
    end
  
    def update
        @profile = current_user.profile || current_user.build_profile
      if @profile.update(profile_params)
        redirect_to profile_path, notice: 'Perfil actualizado correctamente.'
      else
        render :edit
      end
    end
  
    private
  
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :age, :phone, :description, :profile_picture, :email)
    end
  end
  

app/controllers/render_controller.rb
class RenderController < ApplicationController
  def index
    # Acá van las pestañas permitidas en forma de hash!
    views = {
      "main" => "main_page_form",
      "login" => "login_form",
      "article" => "article_form",
      "blog" => "blog_form",
      "search" => "search_form",
      "create_article" => "create_article_form",
      "create_blog" => "create_blog_form",
    }

    # El caso inicial tiene que iniciar la página en el inicio
    view = views[params[:view]] || "main_page_form"

    case view
    when "search_form"
      @search_parameter = params[:query]
      @search_for = params[:search_for] || "articles" 
    
      if @search_for == "articles"
        if params[:by] == "id"
          @results = [Article.find_by(id: @search_parameter)]
        else
          @results = Article.where("title ILIKE ?", "%#{@search_parameter}%").order(updated_at: :desc)
        end
      else
        if params[:by] == "id"
          @results = [Blog.find_by(id: @search_parameter)]
        else
          @results = Blog.where("title ILIKE ?", "%#{@search_parameter}%").order(updated_at: :desc)
        end
      end
    
    when "article_form"
      article_id = params[:query]
      @article = Article.find(article_id)
    
    when "blog_form"
      blog_id = params[:query]
      @blog = Blog.find(blog_id)

    when "create_blog_form"
      article_id = params[:article_id]
      @article = Article.find(article_id)
    end
    # DEFAULT RESPONSE!
    begin
      render view
    rescue ActionView::MissingTemplate
      render "main_page_form"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/render_helper.rb
module RenderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entrega</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <!-- Mostrar mensajes flash -->
    <% flash.each do |key, message| %>
      <div class="alert <%= key == 'alert' ? 'alert-danger' : 'alert-success' %>">
        <%= message %>
      </div>
    <% end %>

    <% if flash[:created] %>
      <script>
        alert("✅ Artículo creado correctamente");
      </script>
    <% end %>

    <header> 
      <h1>WIKI ENTREGA [UNSTABLE]</h1>
      <div>
        <%= link_to "INICIO", root_path(view: "main"), method: :get %>
      </div>
      <div>
        <%= link_to "LOGIN", new_user_session_path, method: :get %>
      </div>
      <% if user_signed_in? %>
        <%= link_to 'MI PERFIL', profile_path(current_user) %>
        
        <!-- Formulario para cerrar sesión con el método DELETE -->
        <%= form_with(url: destroy_user_session_path, method: :delete, local: true) do %>
          <%= submit_tag 'Cerrar sesión' %>
        <% end %>
      <% end %>

    <%= form_with url: root_path, method: :get, local: true do %>
      <%= hidden_field_tag :view, "search" %>

      <label>Search by:</label>
      <!-- [Opción que se muestra, output que se manda al backend] -->
      <%= select_tag :by, options_for_select([["Title", "title"], ["ID", "id"]], params[:by]) %>

      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag "Buscar" %>
    <% end %>

    <div>
      <%= link_to "Crear Articulos", root_path(view: "create_article"), method: :get %>
    </div>

    </header>

    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<h1>Editar perfil</h1>

<%= form_for(@profile, url: profile_path, html: { method: :put, multipart: true }) do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :profile_picture, 'Imagen de perfil' %>
    <%= f.file_field :profile_picture %>
  </div>
  <div>
    <%= f.submit 'Actualizar perfil' %>
  </div>
<% end %>

<%= link_to 'Volver al perfil', profile_path(current_user) %>

app/views/profiles/show.html.erb
<h1>Perfil de <%= @profile.first_name %></h1>

<p>Nombre: <%= @profile.first_name %> <%= @profile.last_name %></p>
<p>Edad: <%= @profile.age %></p>
<p>Teléfono: <%= @profile.phone %></p>
<p>Descripción: <%= @profile.description %></p>
<p>Correo electrónico: <%= @profile.email %></p>

<% if @profile.profile_picture.present? %>
  <%= image_tag @profile.profile_picture.url, width: 200, height: 200 %>
<% else %>
  <p>No tienes imagen de perfil aún.</p>
<% end %>

<%= link_to 'Editar perfil', edit_profile_path %>
<%= button_to "Eliminar cuenta", registration_path(current_user), method: :delete, data: { confirm: "¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer." } %>

app/views/render/article_form.html.erb
<main>
  <script>
    // Better to rework it onto .js folder, then import it as a function.
    function toggleEditForm() {
      const display = document.getElementById("article-display");
      const form = document.getElementById("article-edit-form");
      const edit_button = document.getElementById("edit-cancel-button");

      if (form && display) {
        if (form.style.display === "none") {
          form.style.display = "block";
          display.style.display = "none";
          edit_button.innerText = "CANCELAR";
        } else {
          form.style.display = "none";
          display.style.display = "block";
          edit_button.innerText = "EDITAR";
        }
      }
    }

    function showBlogs() {
      const form = document.getElementById("article-blogs");
      const show_blogs_button = document.getElementById("show-blogs-button");

      if (form) {
        if (form.style.display === "none") {
          form.style.display = "block";
          show_blogs_button.innerText = "Ocultar blogs asociados";
        } else {
          form.style.display = "none";
          show_blogs_button.innerText = "Mostrar blogs asociados";
        }
      }
    }
  </script>

  <h2><%= @article.title %> #<%= @article.id %></h2>
  
  <div id="article-display">
    <p><strong>Descripción:</strong> <%= @article.description %></p>
    <p><strong>Tipo:</strong> <%= @article.info_type %></p>
    <p><strong>Referencias:</strong> <%= @article.references %></p>
  </div>

  <div id="article-edit-form" style="display: none;">
    <%= form_with url: "/articles/#{@article.id}", method: :patch, local: true do %>
      <p>
        <%= label_tag :description, "Titulo" %><br>
        <%= text_field_tag "article[title]", @article.title %>
      </p>
      <p>
        <%= label_tag :description, "Descripción" %><br>
        <%= text_field_tag "article[description]", @article.description %>
      </p>
      <p>
        <%= label_tag :info_type, "Tipo" %><br>
        <%= text_field_tag "article[info_type]", @article.info_type %>
      </p>
      <p>
        <%= label_tag :references, "Referencias" %><br>
        <%= text_field_tag "article[references]", @article.references %>
      </p>
      
      <%= submit_tag "Guardar cambios"%>
    <% end %>
  </div>

  <div id="article-blogs" style="display: none;">
    <h4> Blogs Asociados </h4>
    <% if @article.blogs.empty?%>
      <p> No hay blogs asociados, pero puedes ayudar creando!</p>
    <%else%>
      <% @article.blogs.each do |blog| %>
      <div style="border: 2px solid black; padding: 10px;">
        <p><%= link_to blog.title, render_index_path(view: "blog", query: blog.id) %></p>
        <p><%= blog.description %></p>
      </div>
      <%end%>
    <%end%>
  </div>

  <%= link_to "EDITAR", "#", id: "edit-cancel-button", onclick: "toggleEditForm(); return false;" %>
  <%= link_to "Crear Blog", root_path(view: "create_blog", article_id: @article.id), method: :get %>
  <%= link_to "Blogs Asociados", "#", id: "show-blogs-button", onclick: "showBlogs(); return false;" %>

</main>

app/views/render/blog_form.html.erb
<main>
  <script>
    // Better to rework it onto .js folder, then import it as a function.
    function toggleEditForm() {
      const display = document.getElementById("blog-display");
      const form = document.getElementById("blog-edit-form");
      const edit_button = document.getElementById("edit-cancel-button");

      if (form && display) {
        if (form.style.display === "none") {
          form.style.display = "block";
          display.style.display = "none";
          edit_button.innerText = "CANCELAR";
        } else {
          form.style.display = "none";
          display.style.display = "block";
          edit_button.innerText = "EDITAR";
        }
      }
    }
  </script>

  <h2><%= @blog.title %> #<%= @blog.id %></h2>
  
  <div id="blog-display">
    <p><strong>Descripción:</strong> <%= @blog.description %></p>
    <p><strong>Tipo:</strong> <%= @blog.info_type %></p>
    <p><strong>Editores:</strong> <%= @blog.editors %></p>
    <p><%= link_to "Ver artículo", render_index_path(view: "article", query: @blog.article.id) %></p>

  </div>

  <div id="blog-edit-form" style="display: none;">
    <%= form_with url: "/blogs/#{@blog.id}", method: :patch, local: true do %>
      <p>
        <%= label_tag :description, "Titulo" %><br>
        <%= text_field_tag "blog[title]", @blog.title %>
      </p>
      <p>
        <%= label_tag :description, "Descripción" %><br>
        <%= text_field_tag "blog[description]", @blog.description %>
      </p>
      <p>
        <%= label_tag :info_type, "Tipo" %><br>
        <%= text_field_tag "blog[info_type]", @blog.info_type %>
      </p>
      <p>
        <%= label_tag :references, "Editores" %><br>
        <%= text_field_tag "blog[editors]", @blog.editors %>
      </p>

      <%= submit_tag "Guardar cambios"%>
    <% end %>
  </div>
  
  <div style="padding-bottom: 10px; margin-bottom: 10px;"> 
    <%= link_to "EDITAR", "#", id: "edit-cancel-button", onclick: "toggleEditForm(); return false;" %>
  </div>

  <div>
    <%= form_with url: "/blogs/#{@blog.id}", method: :delete, local: true do %>
      <%= submit_tag "DELETE" %>
    <%end%> 
  </div>
 

</main>

app/views/render/create_article_form.html.erb
<main>
  <h2> MENÚ PARA CREAR ARTICULOS!!!</h2>
  <p> Inserte los campos y aprete crear </p>
  <%= form_with url: articles_path, method: :post do %>
    <div>
      <%= label_tag :title, "Título" %>
      <%= text_field_tag "article[title]" %>
    </div>
    
    <div>
      <%= label_tag :description, "Descripción" %>
      <%= text_field_tag "article[description]" %>
    </div>
    
    <div>
      <%= label_tag :info_type, "Tipo de info" %>
      <%= text_field_tag "article[info_type]" %>
    </div>

    <div> 
      <%= label_tag :references, "Referencias" %>
      <%= text_field_tag "article[references]" %>
    </div>
  
    <%= submit_tag "Crear" %>

  <% end %>

</main>

app/views/render/create_blog_form.html.erb
<main>
  <h2> MENÚ PARA CREAR BLOGS!!!</h2>
  <p> Inserte los campos y aprete crear </p>

  <%= form_with url: blogs_path, method: :post do %>
    <%= hidden_field_tag "blog[article_id]", @article.id %>
    <div>
      <%= label_tag :title, "Título" %>
      <%= text_field_tag "blog[title]" %>
    </div>
    
    <div>
      <%= label_tag :description, "Descripción" %>
      <%= text_field_tag "blog[description]" %>
    </div>
    
    <div>
      <%= label_tag :info_type, "Tipo de info" %>
      <%= text_field_tag "blog[info_type]" %>
    </div>

    <div> 
      <%= label_tag :references, "Referencias" %>
      <%= text_field_tag "blog[references]" %>
    </div>
  
    <%= submit_tag "Crear" %>

  <% end %>

  <h3> REFERENCIAS </h3>
  <p><strong><%= @article.title %> #<%= @article.id %></p>
  

</main>

app/views/render/main_page_form.html.erb
<main>
  <div>
    <h2>MAIN PAGE</h2>
    <p> Para agregar css styles hay que agregarlos en app/stylesheets/application.bootstrap.scss y agregar el estilo que queramos. Luego hay que compilarlo con yarn build:css y listo!</p>
    
  </div>

</main>

app/views/render/search_form.html.erb
<main>
  <div>
    <h1>RESULTADOS</h1>
    <div>
      <%= link_to "ARTÍCULOS", root_path(view: "search", search_for: "articles", by: params[:by], query: params[:query]), method: :get %>
      <%= link_to "BLOGS", root_path(view: "search", search_for: "blogs", by: params[:by], query: params[:query]), method: :get %>
    </div>
    <p> Se muestran resultados de <%= @search_parameter %></p>
    
    <% if @results.present? && @results != [nil] %>
      <% if @search_for == "articles" %>
        <% @results.each do |article| %>
          <div style="border: 2px solid black; padding: 10px;">
            <%= link_to article.title, render_index_path(view: "article", query: article.id) %>  
            #<%= article.id %>
            <p> DESCRIPCIÓN: <%= article.description %></p>
            <p> Fecha de creación: <%= article.created_at %></p>
            <p> Última edición: <%= article.updated_at %></p>
          </div>
        <% end %>
      <% else %>
        <% @results.each do |blog| %>
          <div style="border: 2px solid black; padding: 10px;">
            <%= link_to blog.title, render_index_path(view: "blog", query: blog.id) %>
            #<%= blog.id %>
            <p> DESCRIPCIÓN: <%= blog.description %></p>
            <p> Fecha de creación: <%= blog.created_at %></p>
            <p> Última edición: <%= blog.updated_at %></p>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p>No results found.</p>
    <% end %>
    
    <%= link_to "CAMBIAR PESTAÑA", root_path(view: "main"), method: :get %>
  </div>

</main>

app/views/render/tralalero.html.erb
<main class="container">
  <div class="row text-center justify-content-center">
    <div class="col">

      <div class="tenor-gif-embed" data-postid="9781035983536344817" data-share-method="host" data-aspect-ratio="1.2029" data-width="100%"><a href="https://tenor.com/view/tralalelo-tralalala-gif-9781035983536344817">Tralalelo Tralalala GIF</a>from <a href="https://tenor.com/search/tralalelo+tralalala-gifs">Tralalelo Tralalala GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

      <h1>TRALALERO TRALALA</h1>
      
      
    </div>
  </div>
</main>